public class ContractResetActiveCheckBoxController {
   /* public static void updateRecord(String recordtypeID){
        system.debug('>>>recordId'+recordtypeID);
        
        Contract__c contractObj = [SELECT id,Forcefully_Deactivate__c FROM Contract__c Where id =:recordtypeID];
        system.debug('>>>recordId'+contractObj.Forcefully_Deactivate__c);
        if(contractObj.Forcefully_Deactivate__c == true){
            system.debug('>>>here');
            contractObj.Last_Deactivation_Date__c = null;    
        }
        else{
            contractObj.Forcefully_Deactivate__c=true;
            contractObj.Last_Deactivation_Date__c = system.today();}
       update contractObj;
        
    }*/

}