public with sharing class DoorSalesPerformance {

    public Double april {get;set;}
    public Double may {get;set;}
    public Double june{get;set;}
    public Double july {get;set;}
    public Double august {get;set;}
    public Double september {get;set;}
    public Double october {get;set;}
    public Double november {get;set;}
    public Double december {get;set;}
    public Double january {get;set;}
    public Double february {get;set;}
    public Double march {get;set;}
    public String hoyaAccountId{get;set;}
    public String company{get;set;}
    public String segmentationBox{get;set;}
    public String companyName{get;set;}
    public Double potential{get;set;}
    public Double annual{get;set;}
    public Double sow{get;set;}

    public DoorSalesPerformance() {

    }

}