@isTest public class ServiceFlow_UpdateTaskBatchTest {
    public static Id accontRecordTypeName = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Eye Doctor').getRecordTypeId();
    public static Id caseRecordTypeName = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('ServiceFlow Case Create').getRecordTypeId();
    public static Id taskRecordTypeName = Schema.getGlobalDescribe().get('Task').getDescribe().getRecordTypeInfosByName().get('serviceFlow_AgentCreateCall').getRecordTypeId();
    
    @testSetup static void setup() {
        List<Case> testCases = new List<Case>();
        Account accObj = new Account(
            RecordTypeId = accontRecordTypeName,
            Name = '4151982 - Rachyls Eyes 4 U',
            Shop_Name__c = 'Rachyls Eyes 4 U',
            Account_Status__c = 'Open',
            Phone = '844-736-5773',
            Hoya_Account_ID__c = '4151982',
            NumberOfEmployees = 10,
            DMU__c = 'The Big Nacho Rachyl',
            First_Competitor_global_name__c = 'HOYA',
            First_Competitor_local_name__c = 'HOYA',
            CHCUSTCLASSIFICATIONID__c = 'Ind',
            CHINTERNATIONALGROUP__c = 0,
            Visionary_Alliance__c = 'none',
            Language__c = 'en-us',
            Portal__c = 'usportal',
            Myo_Smart_AuthorizeDealer__c = true,
            Myo_Smart_TrainingComplete__c = false,
            Myo_Kids_Corner__c = true,
            Hoya_Local_Mkt_Campaign_1__c = false,
            Hoya_Local_Mkt_Campaign_2__c = false,
            Onboarding_Customer__c = false,
            Target_List__c = false,
            Potential__c = 0.00,
            Payment_issue__c = false,
            Agreed_Visits__c = 0,
            Financial_Status__c = 'Regular',
            Hunting_Status__c = 'C'
        );
        insert accObj;
        
        Contact conObj = new Contact(
            AccountId = accObj.Id,
            Email = 'testuserhoya@yopmail.com',
            Do_not_visit__c = false,
            Phone = '844-736-5773',
            DoNotCall = false,
            HasOptedOutOfEmail = false,
            HasOptedOutOfFax = false,
            Language_Pick__c = 'English ‎(US)‎',
            Invite_Portal_Email__c = 'HOYA Hub',
            Send_Registration_Email_Flag__c = false,
            LastName = 'test User'
        );
        insert conObj;
        
        Task sobj = new Task(
            Status = 'Closed',
            Account__c = accObj.Id,
            Priority = 'Low',
            serviceFlow_Origin__c = 'Social Media',
            WhoId = conObj.Id,
            serviceFlow_User_Country__c = 'USA',
            WhatId = accObj.Id,
            SFlow_Subject__c = 'Accounting or finance',
            SFlow_Sub_Subject__c = 'Statement copy',
            recordtypeId = taskRecordTypeName
        );
        insert sobj;
    }
    
    @isTest public static void testBatchJob() {
        Test.startTest();
        ServiceFlow_UpdateTaskBatch batchJob = new ServiceFlow_UpdateTaskBatch();
        Database.executeBatch(batchJob);
        Test.stopTest();
        
        // Verify that the tasks were updated
        List<Task> updatedTasks = [
            SELECT Id, ActivityDate, LastModifiedDate
            FROM Task
        ];
        System.assertEquals(1, updatedTasks.size());
    }
}