/**
 *  Test class for trigger Travel_Request_Share_With_Manager
 *
 @author    Juillet Yuan
 @created   2015-02-11
 @version   1.0
 @since     31.0 (Force.com ApiVersion)
 *
 @changelog
 * 2015-02-11 Juillet Yuan <Juillet.Yuan@itbconsult.com>
 * - Created
 * -test coverage--100%
 */
@isTest(seeAllData = false)
private class TrgTravelRequest_ShareWithManager_Test {
	static testmethod void testContactAI(){
		/*
		User u = new User();
        u.FirstName ='First1';
        u.LastName = 'Tester1';
        u.Alias = 'mtst1';
        u.Email = 'mtester1@ItbTestcompany.com';
        u.Username = u.Email;
        u.CommunityNickname = u.Alias;
        u.ProfileId = [select Id 
                        from Profile
                        where Name = 'System Administrator'][0].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
		
		insert u;
		
		User u2 = new User();
        u2.FirstName ='First2';
        u2.LastName = 'Tester2';
        u2.Alias = 'mtst2';
        u2.Email = 'mtester2@ItbTestcompany.com';
        u2.Username = u2.Email;
        u2.CommunityNickname = u2.Alias;
        u2.ProfileId = [select Id 
                        from Profile
                        where Name = 'System Administrator'][0].Id;
        u2.TimeZoneSidKey = 'America/Chicago';
        u2.LocaleSidKey = 'en_US';
        u2.EmailEncodingKey = 'UTF-8';
        u2.LanguageLocaleKey = 'en_US';
		u2.ManagerId = u.Id;
		insert u2;
		*/
		//system.runAs(u2) {
		//	Travel_Request__c  Tr = new Travel_Request__c(Depart_date_outbound_flight__c=system.now(),OwnerId = u2.Id);
		//	test.startTest();
			//insert Tr;
		//	test.stopTest();
		//}
		
	}
}