public class WAEG_Constants {
    
    public static final String REGISTRATION_EMAIL_SENT = 'Email was successfully sent to the customer.';
    public static final String NOT_SHOP_OWNER_OR_REGISTERED = 'Contact is not a Shop Owner or is already registered.';
    public static final String EMAIL_NOT_FILLED_IN = 'Contact Email is not filled in.';
    public static final String SHOP_OWNER_RT = 'Shop_Owner';
    public static final String SEND_REGISTRATION_EMAIL_FLAG = 'Email was already sent to the customer';
    public static final String CHOOSE_PORTAL = 'Please choose portal to send email';
    public static final String HOYA_LEARNING_CENTER = 'HOYA Learning Center';
    public static final String PORTAL_OR_TEMPLATE_NULL = 'Account Portal or Account Template is not filled in';

}